# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\madified.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5 import QtCore, QtGui, QtWidgets 
from PyQt5.QtWidgets import QMainWindow , QApplication
from PyQt5.QtWebEngineWidgets import *
from PyQt5.QtPrintSupport  import *
from PyQt5.QtCore import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("#centralwidget,#moveFrame{\n"
"    background-color: rgb(42, 42, 42);\n"
"}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.moveFrame = QtWidgets.QFrame(self.centralwidget)
        self.moveFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.moveFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.moveFrame.setObjectName("moveFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.moveFrame)
        self.horizontalLayout.setContentsMargins(0, -1, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.logo1 = QtWidgets.QLabel(self.moveFrame)
        self.logo1.setMinimumSize(QtCore.QSize(30, 30))
        self.logo1.setStyleSheet("background-color:rgb(142, 176, 27);\n"
"border-radius:15px;")
        self.logo1.setText("")
        self.logo1.setObjectName("logo1")
        self.horizontalLayout.addWidget(self.logo1)
        self.logo2 = QtWidgets.QLabel(self.moveFrame)
        self.logo2.setMinimumSize(QtCore.QSize(30, 30))
        self.logo2.setStyleSheet("background-color:rgb(142, 176, 27);\n"
"border:4px solid rgb(45, 45, 45);\n"
"border-radius:15px;\n"
"")
        self.logo2.setText("")
        self.logo2.setObjectName("logo2")
        self.horizontalLayout.addWidget(self.logo2)
        self.logo3 = QtWidgets.QLabel(self.moveFrame)
        self.logo3.setMinimumSize(QtCore.QSize(30, 30))
        self.logo3.setStyleSheet("background-color:rgb(45, 45, 45);\n"
"border-radius:15px;")
        self.logo3.setText("")
        self.logo3.setObjectName("logo3")
        self.horizontalLayout.addWidget(self.logo3)
        self.name = QtWidgets.QLabel(self.moveFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.name.sizePolicy().hasHeightForWidth())
        self.name.setSizePolicy(sizePolicy)
        self.name.setMinimumSize(QtCore.QSize(30, 30))
        self.name.setStyleSheet("colour:rgb(144, 144, 144);\n"
"\n"
"background-color: rgb(0, 170, 0);\n"
"background-color: rgb(0, 85, 0);\n"
"background-color: rgb(0, 0, 127);\n"
"background-color: rgba(89, 102, 52,1);\n"
"border-radius:15px;")
        self.name.setAlignment(QtCore.Qt.AlignCenter)
        self.name.setObjectName("name")
        self.horizontalLayout.addWidget(self.name)
        self.minimizBtn = QtWidgets.QPushButton(self.moveFrame)
        self.minimizBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.minimizBtn.setStyleSheet(":hover{\n"
"    background-color: rgba(156, 156, 156,0.6);\n"
"\n"
"}")
        self.minimizBtn.setText("")
        self.minimizBtn.setObjectName("minimizBtn")
        self.horizontalLayout.addWidget(self.minimizBtn)
        self.maximizBtn = QtWidgets.QPushButton(self.moveFrame)
        self.maximizBtn.setMinimumSize(QtCore.QSize(30, 30))
        self.maximizBtn.setStyleSheet(":hover{\n"
"    background-color: rgba(156, 156, 156,0.6);\n"
"\n"
"}")
        self.maximizBtn.setText("")
        self.maximizBtn.setObjectName("maximizBtn")
        self.horizontalLayout.addWidget(self.maximizBtn)
        self.closeBTn = QtWidgets.QPushButton(self.moveFrame)
        self.closeBTn.setMinimumSize(QtCore.QSize(30, 30))
        self.closeBTn.setStyleSheet(":hover{\n"
"    background-color: rgba(255, 50, 35,0.9);\n"
"\n"
"}")
        self.closeBTn.setText("")
        self.closeBTn.setObjectName("closeBTn")
        self.horizontalLayout.addWidget(self.closeBTn)
        self.verticalLayout.addWidget(self.moveFrame, 0, QtCore.Qt.AlignTop)
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.backBtn = QtWidgets.QPushButton(self.frame_2)
        self.backBtn.setText("")
        self.backBtn.setObjectName("backBtn")
        self.horizontalLayout_2.addWidget(self.backBtn)
        self.forwardBtn = QtWidgets.QPushButton(self.frame_2)
        self.forwardBtn.setText("")
        self.forwardBtn.setObjectName("forwardBtn")
        self.horizontalLayout_2.addWidget(self.forwardBtn)
        self.refreshBtn = QtWidgets.QPushButton(self.frame_2)
        self.refreshBtn.setText("")
        self.refreshBtn.setObjectName("refreshBtn")
        self.horizontalLayout_2.addWidget(self.refreshBtn)
        self.urlbar = QtWidgets.QLineEdit(self.frame_2)
        self.urlbar.setMinimumSize(QtCore.QSize(0, 25))
        self.urlbar.setStyleSheet("background-color:rgba(31,31,31,0.8);\n"
"border-radius:5px;\n"
"color : rgb(144, 144, 144);\n"
"padding-left:5px;")
        self.urlbar.setObjectName("urlbar")
        self.horizontalLayout_2.addWidget(self.urlbar)
        self.verticalLayout.addWidget(self.frame_2, 0, QtCore.Qt.AlignTop)
        self.webViewer = QWebEngineView(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.webViewer.sizePolicy().hasHeightForWidth())
        self.webViewer.setSizePolicy(sizePolicy)
        self.webViewer.setStyleSheet("background-color:rgb(    45, 45, 45);\n"
"")
        self.webViewer.setObjectName("webViewer")
        self.verticalLayout.addWidget(self.webViewer)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setStyleSheet("background-color:rgb(45, 45, 45);\n"
"border-bottom-left-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"color:rgb(144, 144,144);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label, 0, QtCore.Qt.AlignBottom)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.name.setText(_translate("MainWindow", "Viginie"))
        self.label.setText(_translate("MainWindow", "....@gmail.com"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
